# Generated by Django 5.2.6 on 2025-09-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default='General', max_length=100),
        ),
    ]
